version: "3.8"

services:
    app:
        container_name: app
        build:
            context: ./docker/php
            network: host
        networks:
            - network
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www

    db:
        container_name: db
        image: mariadb:latest
        cap_add:
            - SYS_NICE
        networks:
            - network
        restart: always
        environment:
            MYSQL_DATABASE: test_task_db
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: test_task_user
            MYSQL_PASSWORD: 123
        ports:
            - '3307:3306'
        volumes:
            - ./docker/mysql/db_data:/var/lib/mysql
            - ./docker/mysql/dumps:/docker-entrypoint-initdb.d

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        networks:
            - network
        ports:
            - "6379:6379"
        command: "redis-server --appendonly yes --requirepass 123"
        volumes:
            - ./docker/redis/db_d–∞ta:/root/redis
        environment:
            - REDIS_PORT=6379

    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            network: host
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - db
            - app

    queues:
        build: ./docker/php
        container_name: queues
        command: php artisan horizon
        restart: always
        networks:
            - network
        working_dir: /var/www
        volumes:
            - ./:/var/www

networks:
  network:
    driver: bridge
